dist: trusty
language: python
python:
- '3.6'
install:
- pip install tox-travis
script:
- tox -r
deploy:
  provider: pypi
  skip_cleanup: true
  skip_existing: true
  user: thclark
  password:
    secure: T6+KupXNqSjbvyUX5y0+/FXrZ2ldA66nSOwbL2lj3LfHXaCfeKK3IEKDivPl+Edyftun9xeOcQ6qgD3aIjlBlYKZ3z6iD1hLDbkDh0ngrgC75Pngi39k01rOUCkbtjKXvdmRK9Yka3WLbaOdhwzQoKdau1Ecxt+kedmdSjwJ0c8Fuk519x3xx3AyqaBNq4cuaQS6veXGeAX6jZLAHmeAS4kpNUXtEbDLXKGmB9u1dV/5DrOtxNLziV/UA7OhfXUZsFEbGhARGuZ6Dh9ltrkSV+tZICUU1HV2xVkMqEI4zlC61o2jd2bYMwxglARzAIpfUml7oLDH6l6iuTO89Fc07/F0CgcNQkEn8P4Gi/pssujlYegGJMRTLVPncdvxC+GQwnjOvEVOQ9na1OdyJfwTWOQiGq3TedHJEgug74n8265EgJmVfJOZqJRHCaYz8wfMbHrqO73vIg4C7czrWpV+GZWiYIuuiX5W54nQ0HwHDxyOL00tMxCdNeWHSWe+fgUCfR4k9yxaFYF7yAQhNaJM0oQcb85/p2KhM0xLUbiv8AzEl4Ya6giqYKdAjHyI+cDehcgYk85ShGnkRBwxlpHTYed19RGEVJ7r7cfaJ5XsNM4IyMBnP4pYUSjRJ42+zNlod9zy3CitNvS6YYCWevjcfBns+rMb3Jz0G6NFyMRP1Ko=
  on:
    branch: master
