dist: trusty
language: python
python:
- '3.6'
install:
- pip install tox-travis
script:
- tox -r
deploy:
  provider: pypi
  skip_cleanup: true
  skip_existing: true
  user: thclark
  password:
    secure: PfDmNnzzID+Bav+bFocfdX7f9IlNFlaMGWQ4W10gfOx+eiuhoPY3S4L+tGWzxg08CnNopiD6SuF7nlMpn1+ycyuM/RJSDZPxsSLNNoCQElCJPFMnfcURdFaMS6pIB84nUQHDx7VMu+1H4kULWj2IPhKiuAzvqjZs/an7H4EZGgBag2jYVuBaEuuVBG8xytzAodcstzj9RkYdhfpkWWmSsEh1hU3RLUBPKbRertAiCnkOFFYF3tV4yVVXh96RQBThv1Mb+tB7/n/+bkbjQbUCE4e1McEFulGVBG0AhMGed7wKEGvPUwxi1t5ZcuIHpHSnSS0aqQalgUN7xNmNgdgqGmQuCfVmHOKn0QoaXbqALwoz8wdU6mz5DMmq48tR7HRtNmiUWbJBYVgQdugRlmhYV7Eez9qesbixoKasit4iFD3/ORGaUMLqTr2uTt6PLO/vn+/W5uHVVyJUzjzqYHobtIDGRSGJMgJWFeekx7839TAWoqTuOi3hx2J9jzaA6sEpmj+sfiC+2ecLprkPhYL1qQBUvTmrxi4VuZI9Q7sKV/Z5lyRrwBZ390BxTTTPGiQLutckOf83eIxwTE0yHSbqK8Gp1Gk7vrf13Y5SQ2tD1a/x5j+W/fY+uMPgdI2Kq/VuDy35oWT99SuYrcGxhMHZCLyOwPhSl5hIgcGFmal9mcw=
  on:
    branch: master
