dist: trusty
language: python
python:
- '3.6'
install:
- pip install tox-travis
script:
- tox -r
deploy:
  provider: pypi
  skip_cleanup: true
  skip_existing: true
  user: thclark
  password:
    secure: Xse4ugZHNw8hTODPB+DazOVbyLK+R5xUVJLQFMo3Cjlp94oc1F4vwMXMHXEowhsoqZv1nrlH9zY1WA4LPhZtOOXlmch4AgHIWt23r4TRJQXsJW1qIfT21FOnXjtrVGyrObJXkD+SUserwMua7OBnPJ5ZgnflBErdONz5QG1ozLxg5cQMJ8jW58aW20N/ZCyRnAWXG9neWrBpXTJAzXN8caRG3FUjROzQOoQ/vkHb7hKPBy/hmnWALLHQAGe8KTK1uhnqd0YyxZ1Yohz6332xha8yYosRlLN4doztKbWWWDQA4ZWPQu1g+btYawTuSUPL5C7HERJuu84alkCtlL7zzGJF0N5e540f2y/PoQo9cROFu4aqPjUnPj9oipQLWP+nqviws980PXRwpqg/oCl1yCRA/Suryqe1nzCqYjGhRYvKDzK4sFw+cLT1aCRjchlk0ZlPMC6gHgiUdXw7ZTS9c/xldsxIlKwUmjERPQiCYg5iyNw46wzVgk4GRLFf5duLGFWuXcOeMOgMn4lnXVy9anN7irSQrZ3qSApBPG2Mtwy8TEsCqRXjwcunOPlKVWftZ6Wp8yrlwPvw7SiMjjcBzBrVzFjit7Rg5BHYIq+MVpMmvMuqq4vqAud7QD9m4BAWs9wFM7arPMqqnsAY3SyeJyr9479q3S950A2bN6EnLWc=
  on:
    branch: master
