dist: trusty
language: python
python:
- '3.6'
install:
- pip install tox-travis
script:
- tox -r
deploy:
  provider: pypi
  skip_cleanup: true
  skip_existing: true
  user: thclark
  password:
    secure: NR7u8D/HyzEpwrLpXtYkWYw099JBphrJqDVlWdyO93zH1EG4nL1c5Ymh0GXKW6YP38eaDDOYd8OEQlDe6de5iR1FLEN+EFszqi5qvSRO62eW2YEbs9dcePxMciiEqlTD5/TIkpmbB+oO376gMtd2KquG4Z3ViXKsbmCcGRzOQE3Kc0RB43yuOftFriLigNz/Yirfw1mjFK3sakqSUqmQ0krwlM2HTo0uziagbH2D/TMZ6xcjiQDdnileXIqtQITBbAmn08yAMj+y33stgG3WlzEC4ZKyzcke4bjTCnR49XAdNqEbWEeRKJB/k5nf5AdOI3hUipgxMPzNCwT+Pv4Qm6FBrctMyJulI+pDmu3kkN4e1J7KiPjoqHsYInkx90Sa5mwtLpv7XZT/j+Hu88RUpW+c1nBldARzriX6+im5HVZHe+BpIWOnb5CO5jQt+AMUjxYn1CuLSMMuyDmbJcxU8LwmQnzBYTF/bqkaB6x0pg90vb4cZh+ydiWHIEQlUu0sfCOrfVSMZMRUmSlQeqFPUgIFbcGnlc4wiUSq18dNxEySTjrjkw01+r/524oDbfIMGtNYqyxlpFc2eotnXWQU6k6p4mdXXR9f4fBO8YyB+YqBdg6Bw45cO7TUmY3VQqxdF6ugtIPmvGMItfI3t4rgr4A92k8j2FuZodPTshAwNhE=
  on:
    branch: master
