# Generated by Django 2.1.8 on 2019-05-31 13:19

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail_site_sections.blocks.base


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_site_sections', '0002_hashes_help_and_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='body',
            field=wagtail.core.fields.StreamField([('team_section', wagtail.core.blocks.StructBlock([('hash', wagtail_site_sections.blocks.base.HashBlock(help_text="Allow navigation to this section within a page. e.g. 'team' allows navigation to /http://your-site.com/#team", label='Hash', max_length=80, required=False)), ('description', wagtail.core.blocks.TextBlock(default='Here is a list of our Head Peeps. They look glorious rendered in HTML but are probably just normal, mortal humans.', label='Description', max_length=400, required=False)), ('members', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(label='Name', max_length=80, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Photo', required=True)), ('role', wagtail.core.blocks.CharBlock(label='Role / Job Title', max_length=80, required=True)), ('biography', wagtail.core.blocks.TextBlock(label='Bio', required=False)), ('linkedin', wagtail.core.blocks.URLBlock(label='LinkedIn Page', required=False)), ('twitter', wagtail.core.blocks.URLBlock(label='Twitter Page', required=False))]), label='Team Members'))]))], blank=True, help_text='Add sections to the page'),
        ),
    ]
